### ISSUE TITLE
Allow others extensions for assets

### ISSUE THREAD

**Issue by marceloavf** [mikaelkrief/GitHub-Tools-vsts-extensions#5]
I'm working with a frequently update that uses a `.exe` directly, should be a way to work with others extensions, even `7z` that uses `LZMA` powerful compression.

**Comment by mikaelkrief** [comment]
Great @marceloavf ! I will work on that.

**Comment by marceloavf** [comment]
No problem @mikaelkrief, just review the pull request when you have time, thanks!

**Comment by mikaelkrief** [comment]
Published
